[package]
name = "cladding"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
libc = "0.2.170"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
